/**
 * Vite client type declarations.
 *
 * This triple-slash reference directive imports the TypeScript type definitions
 * provided by Vite.  These types enable:
 *
 * - `import.meta.env` — type-safe access to environment variables (e.g.,
 *   `import.meta.env.DEV` is `true` in development, `false` in production).
 * - `import.meta.hot` — type-safe access to the Vite HMR (Hot Module
 *   Replacement) API for custom update handlers.
 * - Static asset imports — types for importing CSS, images, SVGs, and other
 *   non-JavaScript files that Vite handles (e.g.,
 *   `import logo from "./logo.svg"` resolves to a string URL).
 *
 * This file is generated by Vite and should not be edited manually.
 * It must be present for the TypeScript compiler to recognise Vite-specific
 * globals without error.
 */
/// <reference types="vite/client" />
